/*
 * 3GPP SBI ProblemDetails cause values (lab / Model D)
 */

#if !defined(OGS_SBI_INSIDE) && !defined(OGS_SBI_COMPILATION)
#error "This header cannot be included directly."
#endif

#ifndef OGS_SBI_CAUSE_H
#define OGS_SBI_CAUSE_H

#define OGS_SBI_CAUSE_INVALID_MSG_FORMAT              "INVALID_MSG_FORMAT"
#define OGS_SBI_CAUSE_INVALID_QUERY_PARAM             "INVALID_QUERY_PARAM"
#define OGS_SBI_CAUSE_MANDATORY_IE_MISSING            "MANDATORY_IE_MISSING"
#define OGS_SBI_CAUSE_MANDATORY_IE_INCORRECT          "MANDATORY_IE_INCORRECT"
#define OGS_SBI_CAUSE_MANDATORY_QUERY_PARAM_MISSING   "MANDATORY_QUERY_PARAM_MISSING"
#define OGS_SBI_CAUSE_OPTIONAL_IE_INCORRECT           "OPTIONAL_IE_INCORRECT"
#define OGS_SBI_CAUSE_OPTIONAL_QUERY_PARAM_INCORRECT  "OPTIONAL_QUERY_PARAM_INCORRECT"
#define OGS_SBI_CAUSE_UNSPECIFIED_MSG_FAILURE         "UNSPECIFIED_MSG_FAILURE"

#define OGS_SBI_CAUSE_USER_NOT_FOUND                  "USER_NOT_FOUND"
#define OGS_SBI_CAUSE_DATA_NOT_FOUND                  "DATA_NOT_FOUND"
#define OGS_SBI_CAUSE_UNSUPPORTED_RESOURCE_URI        "UNSUPPORTED_RESOURCE_URI"
#define OGS_SBI_CAUSE_AUTHENTICATION_REJECTED         "AUTHENTICATION_REJECTED"
#define OGS_SBI_CAUSE_SERVING_NETWORK_NOT_AUTHORIZED  "SERVING_NETWORK_NOT_AUTHORIZED"

#define OGS_SBI_CAUSE_CONTEXT_NOT_FOUND               "CONTEXT_NOT_FOUND"
#define OGS_SBI_CAUSE_UE_NOT_REACHABLE                "UE_NOT_REACHABLE"
#define OGS_SBI_CAUSE_TEMPORARY_REJECT_REGISTRATION_ONGOING \
    "TEMPORARY_REJECT_REGISTRATION_ONGOING"

#define OGS_SBI_CAUSE_NF_DISCOVERY_FAILURE            "NF_DISCOVERY_FAILURE"
#define OGS_SBI_CAUSE_NF_SELECTION_FAILURE              "NF_SELECTION_FAILURE"
#define OGS_SBI_CAUSE_TARGET_NF_NOT_REACHABLE         "TARGET_NF_NOT_REACHABLE"
#define OGS_SBI_CAUSE_NRF_NOT_REACHABLE               "NRF_NOT_REACHABLE"
#define OGS_SBI_CAUSE_SCP_INTERNAL_ERROR              "SCP_INTERNAL_ERROR"

#endif /* OGS_SBI_CAUSE_H */
